// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
// defineApp
export { defineApp } from './core/defineApp'
export type { RuntimeConfig } from './core/defineApp'
// plugins
export { useRequest, UseRequestProvider, request, getRequestInstance } from 'D:/agent-customer/src/.umi/plugin-request';
// plugins types.d.ts
export * from 'D:/agent-customer/src/.umi/plugin-request/types.d';
// @umijs/renderer-*
export { createBrowserHistory, createHashHistory, createMemoryHistory, Helmet, HelmetProvider, createSearchParams, generatePath, matchPath, matchRoutes, Navigate, NavLink, Outlet, resolvePath, useLocation, useMatch, useNavigate, useOutlet, useOutletContext, useParams, useResolvedPath, useRoutes, useSearchParams, useAppData, useClientLoaderData, useLoaderData, useRouteProps, useSelectedRoutes, useServerLoaderData, renderClient, __getRoot, Link, useRouteData, __useFetcher, withRouter } from 'D:/agent-customer/node_modules/.pnpm/@umijs+renderer-react@4.6.8_b462d5bdca8d4e59f9f87c7f27495787/node_modules/@umijs/renderer-react';
export type { History, ClientLoader } from 'D:/agent-customer/node_modules/.pnpm/@umijs+renderer-react@4.6.8_b462d5bdca8d4e59f9f87c7f27495787/node_modules/@umijs/renderer-react'
// umi/client/client/plugin
export { ApplyPluginsType, PluginManager } from 'D:/agent-customer/node_modules/.pnpm/umi@4.6.84_@babel+core@7.29_4f8a812dee4783f323d65e28af84827a/node_modules/umi/client/client/plugin.js';
export { history, createHistory } from './core/history';
export { terminal } from './core/terminal';
// react ssr
export const useServerInsertedHTML: Function = () => {};
// test
export { TestBrowser } from './testBrowser';
